package constant

const (
	PORT string = "PORT"

	URL_OMDB string = "URL_OMDB"
	API_KEY  string = "API_KEY"

	POSTGRE_USERNAME string = "POSTGRE_USERNAME"
	POSTGRE_PASSWORD string = "POSTGRE_PASSWORD"
	POSTGRE_PORT string = "POSTGRE_PORT"
	POSTGRE_ADDRESS string = "POSTGRE_ADDRESS"
	POSTGRE_DB string = "POSTGRE_DB"
)

